# Generated by Django 5.0.13 on 2025-05-28 11:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seminariopage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminariopage',
            name='info',
            field=wagtail.fields.StreamField([('foto_banner', 2), ('conclusoes', 6), ('info', 12), ('oradores', 19), ('moderadores', 20), ('video', 22), ('programa', 28), ('contactos', 33), ('generico', 34)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Imagem do Banner'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('foto', 0), ('titulo', 1), ('subtitulo', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descrição do ficheiro', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('ficheiro', 3), ('descricao', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Conclusões'}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 8: ('wagtail.images.blocks.ImageBlock', [], {'label': 'foto que vai ser exibida no cartão'}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Considerações Iniciais (secção de apresentação)', 'required': True}), 10: ('wagtail.blocks.DateBlock', (), {'label': 'Data do Seminário', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição (texto do cartão na home)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('nome', 7), ('foto', 8), ('consIn', 9), ('date', 10), ('desc', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.images.blocks.ImageBlock', [], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Horário de apresentação da palestra', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da palestra', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('nome', 13), ('subtitulo', 13), ('photo', 14), ('biografia', 15), ('horario', 16), ('titulo_palestra', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'lista de oradores'}), 20: ('wagtail.blocks.ListBlock', (18,), {'label': 'lista de moderadores'}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (YouTube, Vimeo, etc)'}), 22: ('wagtail.blocks.StructBlock', [[('video_url', 21)]], {}), 23: ('wagtail.blocks.TimeBlock', (), {'label': 'Horário'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Título'}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Moderador ou nome do palestrante', 'label': 'Subtítulo', 'required': False}), 26: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Destacar com fundo diferente', 'label': 'Destaque?', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('hora', 23), ('titulo', 24), ('responsavel', 25), ('destaque', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'label': 'Programa'}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Morada', 'required': True}), 30: ('wagtail.blocks.EmailBlock', (), {'label': 'Email de contacto', 'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': False}), 32: ('wagtail.blocks.TextBlock', (), {'label': 'Código iframe do mapa (Google Maps, etc.)', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('morada', 29), ('email', 30), ('telefone', 31), ('mapa_embed', 32)]], {}), 34: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Conteúdo genérico'})}),
        ),
    ]
