# Generated by Django 5.0.13 on 2025-06-02 10:01

import gestor_eventos.core.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_seminariopage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminariopage',
            name='info',
            field=wagtail.fields.StreamField([('foto_banner', 2), ('conclusoes', 6), ('info', 12), ('oradores', 15), ('moderadores', 21), ('video', 23), ('programa', 29), ('contactos', 35), ('generico', 36)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Imagem do Banner'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('foto', 0), ('titulo', 1), ('subtitulo', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descrição do ficheiro', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('ficheiro', 3), ('descricao', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Conclusões'}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 8: ('wagtail.images.blocks.ImageBlock', [], {'label': 'foto que vai ser exibida no cartão'}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Considerações Iniciais (secção de apresentação)', 'required': True}), 10: ('wagtail.blocks.DateBlock', (), {'label': 'Data do Seminário', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição (texto do cartão na home)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('nome', 7), ('foto', 8), ('consIn', 9), ('date', 10), ('desc', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.OradoresBlock,), {'label': 'Lista de Oradores'}), 15: ('wagtail.blocks.StructBlock', [[('titulo', 13), ('lista', 14)]], {}), 16: ('wagtail.images.blocks.ImageBlock', [], {}), 17: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 18: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Horário de apresentação da palestra', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da palestra', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('nome', 13), ('subtitulo', 13), ('photo', 16), ('biografia', 17), ('horario', 18), ('titulo_palestra', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'lista de moderadores'}), 22: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (YouTube, Vimeo, etc)'}), 23: ('wagtail.blocks.StructBlock', [[('video_url', 22)]], {}), 24: ('wagtail.blocks.TimeBlock', (), {'label': 'Horário'}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Título'}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Moderador ou nome do palestrante', 'label': 'Subtítulo', 'required': False}), 27: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Destacar com fundo diferente', 'label': 'Destaque?', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('hora', 24), ('titulo', 25), ('responsavel', 26), ('destaque', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Programa'}), 30: ('wagtail.blocks.CharBlock', (), {'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Morada', 'required': True}), 32: ('wagtail.blocks.EmailBlock', (), {'label': 'Email de contacto', 'required': False}), 33: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': False}), 34: ('wagtail.blocks.TextBlock', (), {'label': 'Código iframe do mapa (Google Maps, etc.)', 'required': True}), 35: ('wagtail.blocks.StructBlock', [[('titulo', 30), ('morada', 31), ('email', 32), ('telefone', 33), ('mapa_embed', 34)]], {}), 36: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Conteúdo genérico'})}),
        ),
    ]
