# Generated by Django 5.0.13 on 2025-06-02 10:19

import gestor_eventos.core.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_seminariopage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminariopage',
            name='info',
            field=wagtail.fields.StreamField([('foto_banner', 2), ('conclusoes', 5), ('info', 12), ('oradores', 15), ('moderadores', 17), ('video', 20), ('programa', 26), ('contactos', 31), ('generico', 32)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Imagem do Banner'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('foto', 0), ('titulo', 1), ('subtitulo', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ConclusaoBlock,), {'label': 'Lista de Conclusões'}), 5: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('lista', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.images.blocks.ImageBlock', [], {'label': 'foto que vai ser exibida no cartão'}), 8: ('wagtail.blocks.RichTextBlock', (), {'label': 'Considerações Iniciais (secção de apresentação)', 'required': True}), 9: ('wagtail.blocks.DateBlock', (), {'label': 'Data do Seminário', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição (texto do cartão na home)', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Cor principal', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('nome', 6), ('foto', 7), ('consIn', 8), ('date', 9), ('desc', 10), ('cor', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.OradoresBlock,), {'label': 'Lista de Oradores'}), 15: ('wagtail.blocks.StructBlock', [[('titulo', 13), ('lista', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ModeradoresBlock,), {'label': 'Lista de Moderadores'}), 17: ('wagtail.blocks.StructBlock', [[('titulo', 13), ('lista', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (YouTube, Vimeo, etc)'}), 20: ('wagtail.blocks.StructBlock', [[('titulo', 18), ('video_url', 19)]], {}), 21: ('wagtail.blocks.TimeBlock', (), {'label': 'Horário'}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Título'}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Moderador ou nome do palestrante', 'label': 'Subtítulo', 'required': False}), 24: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Destacar com fundo diferente', 'label': 'Destaque?', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('hora', 21), ('titulo', 22), ('responsavel', 23), ('destaque', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'label': 'Programa'}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Morada', 'required': True}), 28: ('wagtail.blocks.EmailBlock', (), {'label': 'Email de contacto', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': False}), 30: ('wagtail.blocks.TextBlock', (), {'label': 'Código iframe do mapa (Google Maps, etc.)', 'required': True}), 31: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('morada', 27), ('email', 28), ('telefone', 29), ('mapa_embed', 30)]], {}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Conteúdo genérico'})}),
        ),
    ]
