# Generated by Django 5.0.13 on 2025-06-02 11:23

import gestor_eventos.core.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_seminariopage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminariopage',
            name='info',
            field=wagtail.fields.StreamField([('foto_banner', 2), ('conclusoes', 5), ('info', 13), ('oradores', 16), ('moderadores', 18), ('video', 21), ('programa', 27), ('contactos', 32), ('generico', 33)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Imagem do Banner'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('foto', 0), ('titulo', 1), ('subtitulo', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ConclusaoBlock,), {'label': 'Lista de Conclusões'}), 5: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('lista', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 7: ('wagtail.images.blocks.ImageBlock', [], {'label': 'foto que vai ser exibida no cartão'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Titulo da secção de apresentação (deve ser Apresentação)', 'max_length': 255, 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Considerações Iniciais (secção de apresentação)', 'required': True}), 10: ('wagtail.blocks.DateBlock', (), {'label': 'Data do Seminário', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição (texto do cartão na home)', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Cor principal (escrever em hexadecimal, ex: #ff0000)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('nome', 6), ('foto', 7), ('titulo', 8), ('consIn', 9), ('date', 10), ('desc', 11), ('cor', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'required': True}), 15: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.OradoresBlock,), {'label': 'Lista de Oradores'}), 16: ('wagtail.blocks.StructBlock', [[('titulo', 14), ('lista', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ModeradoresBlock,), {'label': 'Lista de Moderadores'}), 18: ('wagtail.blocks.StructBlock', [[('titulo', 14), ('lista', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': False}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (YouTube, Vimeo, etc)'}), 21: ('wagtail.blocks.StructBlock', [[('titulo', 19), ('video_url', 20)]], {}), 22: ('wagtail.blocks.TimeBlock', (), {'label': 'Horário'}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Título'}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Moderador ou nome do palestrante', 'label': 'Subtítulo', 'required': False}), 25: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Destacar com fundo diferente', 'label': 'Destaque?', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('hora', 22), ('titulo', 23), ('responsavel', 24), ('destaque', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'Programa'}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Morada', 'required': True}), 29: ('wagtail.blocks.EmailBlock', (), {'label': 'Email de contacto', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': False}), 31: ('wagtail.blocks.TextBlock', (), {'label': 'Código iframe do mapa (Google Maps, etc.)', 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('morada', 28), ('email', 29), ('telefone', 30), ('mapa_embed', 31)]], {}), 33: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Conteúdo genérico'})}),
        ),
    ]
