# Generated by Django 5.0.13 on 2025-06-02 13:57

import gestor_eventos.core.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_seminariopage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminariopage',
            name='info',
            field=wagtail.fields.StreamField([('cor', 0), ('foto_banner', 3), ('conclusoes', 6), ('info', 13), ('oradores', 16), ('moderadores', 19), ('video', 22), ('programa', 25), ('contactos', 31), ('generico', 32)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Escrever em hexadecimal', 'label': 'Cor principal (escrever em hexadecimal, ex: #ff0000)', 'required': False}), 1: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Imagem do Banner'}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('foto', 1), ('titulo', 2), ('subtitulo', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': "Titulo da secção, deve ser 'Conclusões'", 'required': True}), 5: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ConclusaoBlock,), {'label': 'Lista de Conclusões'}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 4), ('lista', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 8: ('wagtail.images.blocks.ImageBlock', [], {'label': 'foto que vai ser exibida no cartão'}), 9: ('wagtail.blocks.CharBlock', (), {'label': "Titulo da secção de apresentação (deve ser 'Apresentação')", 'max_length': 255, 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Considerações Iniciais (secção de apresentação)', 'required': True}), 11: ('wagtail.blocks.DateBlock', (), {'label': 'Data do Seminário', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição (texto do cartão na home)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('nome', 7), ('foto', 8), ('titulo', 9), ('consIn', 10), ('date', 11), ('desc', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': "Título da secção, deve ser 'Oradores'", 'required': True}), 15: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.OradoresBlock,), {'label': 'Lista de Oradores'}), 16: ('wagtail.blocks.StructBlock', [[('titulo', 14), ('lista', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'label': "Titulo da secção, deve ser 'Moderadores'", 'required': True}), 18: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ModeradoresBlock,), {'label': 'Lista de Moderadores'}), 19: ('wagtail.blocks.StructBlock', [[('titulo', 17), ('lista', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': "Titulo da secção, deve ser 'Transmissão'", 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (YouTube, Vimeo, etc)'}), 22: ('wagtail.blocks.StructBlock', [[('titulo', 20), ('video_url', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'label': "Titulo da secção, deve ser 'Programa'", 'required': False}), 24: ('wagtail.blocks.ListBlock', (gestor_eventos.core.models.ProgramaItemBlock,), {'label': 'items do programa'}), 25: ('wagtail.blocks.StructBlock', [[('titulo', 23), ('lista', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Morada', 'required': True}), 28: ('wagtail.blocks.EmailBlock', (), {'label': 'Email de contacto', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': False}), 30: ('wagtail.blocks.TextBlock', (), {'label': 'Código iframe do mapa (Google Maps, etc.)', 'required': True}), 31: ('wagtail.blocks.StructBlock', [[('titulo', 26), ('morada', 27), ('email', 28), ('telefone', 29), ('mapa_embed', 30)]], {}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Conteúdo genérico'})}),
        ),
    ]
